### ISSUE TITLE
can't build under Angular v4.0.0-rc.5

### ISSUE THREAD

**Issue by byunru** [daominhsangvn/ng2-nvd3#2]
ERROR in Error encountered resolving symbol values statically.
Calling function 'makeDecorator', function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function,
resolving symbol Injectable in
..../node_modules/ng2-nvd3/node_modules/@angular/core/src/di/metadata.d.ts,
resolving symbol OpaqueToken in
..../node_modules/ng2-nvd3/node_modules/@angular/core/src/di/opaque_token.d.ts,

========================= environment ==============================
@angular/cli: 1.0.0-rc.2
node: 7.7.0
os: win32 x64
@angular/animations: 4.0.0-rc.5
@angular/common: 4.0.0-rc.5
@angular/compiler: 4.0.0-rc.5
@angular/core: 4.0.0-rc.5
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.0-rc.5
@angular/http: 4.0.0-rc.5
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0-rc.5
@angular/platform-browser-dynamic: 4.0.0-rc.5
@angular/router: 4.0.0-rc.5
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.5
@angular/platform-server: 4.0.0-rc.5

**Comment by daominhsangvn** [comment]
Try to remove node_modules in feature folder (`.../ng2-nvd3/node_modules`) and try again

**Comment by byunru** [comment]
it works after remove node_modules in feature folder (.../ng2-nvd3/node_modules) ,  
but how to avoid that folder show up during npm install :
npm install --save git+https://github.com/daominhsangvn/ng2-nvd3

**Comment by daominhsangvn** [comment]
i had removed the dependencies in `package.json`, it's fine now
